import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class NavbarService {
  toDisplayMenu = new Subject<any>();

  menuList = [
    {
      menuName: 'Electronics',
      lists: [
        {
          listHeader: 'Electronics',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Cameras',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Washing Machines',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Computers',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Laptops',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },

    {
      menuName: 'TV & Appliances',
      lists: [
        {
          listHeader: 'LED TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'HD+ TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Home Theater',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Smart Devices',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Projector',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },

    {
      menuName: 'Men',
      lists: [
        {
          listHeader: 'LED TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'HD+ TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Home Theater',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Smart Devices',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Projector',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },

    {
      menuName: 'Women',
      lists: [
        {
          listHeader: 'LED TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'HD+ TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Home Theater',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Smart Devices',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Projector',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },
    {
      menuName: 'Baby & Kids',
      lists: [
        {
          listHeader: 'LED TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'HD+ TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Home Theater',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Smart Devices',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Projector',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },
    {
      menuName: 'Home & Furniture',
      lists: [
        {
          listHeader: 'LED TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'HD+ TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Home Theater',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Smart Devices',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Projector',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },
    {
      menuName: 'Sports, Books & More',
      lists: [
        {
          listHeader: 'LED TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'HD+ TVs',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Home Theater',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Smart Devices',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },

        {
          listHeader: 'Projector',
          list: [
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
            'electronics',
          ],
        },
      ],
    },
  ];
}
